routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Dashboard\ProfileController;
use App\Http\Controllers\Dashboard\BookingController;
use App\Http\Controllers\Dashboard\RoomTypeController;
use App\Http\Controllers\Dashboard\RoomController;
use App\Http\Controllers\Dashboard\GuestController;
use App\Http\Controllers\Dashboard\AdministratorController;
use App\Http\Controllers\Dashboard\RestrictionController;
use App\Http\Controllers\Dashboard\ExtraController;
use App\Http\Controllers\Dashboard\OrderController;
use App\Http\Controllers\Dashboard\ServiceController;

use App\Http\Controllers\Portal\HotelFarsundController;
use App\Http\Controllers\Portal\BookingPaymentController;
use App\Http\Controllers\Auth\UserController;
use App\Http\Controllers\LenguageController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HotelFarsundController::class, 'home'])->name('home');
Route::get('sobre-nosotros', [HotelFarsundController::class, 'about'])->name('about');
Route::get('habitaciones', [HotelFarsundController::class, 'rooms'])->name('rooms');
Route::get('reservar/{id}/{chechin?}/{checkout?}', [HotelFarsundController::class, 'book'])->name('book');
Route::get('servicios', [HotelFarsundController::class, 'services'])->name('services');
Route::get('lugares-de-interes', [HotelFarsundController::class, 'placeInterest'])->name('places_interest');
Route::get('contacto', [HotelFarsundController::class, 'contact'])->name('contact');
Route::post('contacto/enviar', [HotelFarsundController::class, 'send'])->name('send.contact');
Route::get('policy-privacy', [HotelFarsundController::class, 'policyPrivacy'])->name('policy.privacy');
Route::get('terms-conditions', [HotelFarsundController::class, 'termsConditions'])->name('terms.conditions');


Route::middleware(['guest'])->group(function () {
    /* User - Farsund */    
    Route::get('sig-up', [UserController::class, 'create'])->name('create.user');
    Route::post('sig-up/store', [UserController::class, 'store'])->name('store.user');
    Route::get('sig-in', [UserController::class, 'login'])->name('login');
    Route::post('sig-in/authentication', [UserController::class, 'authentication'])->name('authentication');
});

Route::middleware('auth')->group(function(){
    /* User - Farsund */    
    Route::get('logout', [UserController::class, 'logout'])->name('logout.user');
    Route::post('reservacion/{room}', [BookingPaymentController::class, 'store'])->name('payment');
    Route::get('confirm', [BookingPaymentController::class, 'show'])->name('confirm');
    Route::get('approbal', [BookingPaymentController::class, 'approbal'])->name('approbal');

});



Route::group(['middleware' => 'admin', 'prefix' => 'dashboard'], function(){
    
    Route::resource('/profile', ProfileController::class);
    Route::get('/profile/edit/datos', [ProfileController::class, 'editProfile'])->name('profile.edit.datos');
    Route::PUT('/profile/update/datos', [ProfileController::class, 'updateProfile'])->name('profile.update.datos');
    Route::get('/profile/edit/password', [ProfileController::class, 'editPass'])->name('profile.edit.password');
    Route::PUT('/profile/update/password', [ProfileController::class, 'updatePass'])->name('profile.update.password');
    Route::resource('/booking', BookingController::class);
    Route::post('/booking/confirm', [BookingController::class, 'confirm'])->name('booking.confirm');
    Route::post('/booking/finish', [BookingController::class, 'finish'])->name('booking.finish');
    Route::resource('/roomtype', RoomTypeController::class);
    Route::resource('/room', RoomController::class);
    Route::resource('/guest', GuestController::class);
    Route::resource('/administrator', AdministratorController::class);
    Route::resource('/restriction', RestrictionController::class);
    Route::resource('/extra', ExtraController::class);
    Route::resource('/order', OrderController::class);
    Route::resource('/service', ServiceController::class);
    
});

/*Lenguage*/
Route::get('lang/{lang}', [LenguageController::class, 'swap'])->name('lang.swap');

app/Models/Extra.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Extra extends Model
{
    use HasFactory;

    protected $fillable = ['name','price','optional'];

    public function setNameAttribute($value)
    {
      $this->attributes['name'] = strtolower($value);
    }

    public function bookings()
    {
        return $this->belongsToMany(Booking::class);
    }

    public function roomTypes()
    {
        return $this->belongsToMany(RoomType::class);
    }
    

}

app/Http/Controllers/Dashboard/AdministratorController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;

class AdministratorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {set_time_limit("1800");
        $administrators = User::where('admin', true)->where('id', '<>', auth()->id())->get();
        return view('administrator.user.administrators.index')->with('administrators', $administrators);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('administrator.user.administrators.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'firstname'  => 'required',
            'lastname'   => 'required',
            'dni'        => 'required|unique:users,dni',
            'phone'      => 'required|numeric|unique:users,phone',
            'email'      => 'required|regex:/(.*)@hotelfarsund\.es$/i|unique:users,email',
            'password'   => 'required|min:8|',
        ],
        [
            'firstname.required'    => 'Introduzca el nombre',
            'lastname.required'     => 'Introduzca el apellido',
            'dni.required'      => 'Introduzca el DNI',
            'dni.unique'        => 'Este DNI ya se encuentra registrado',
            'phone.required'    => 'Introduzca el Telefono',
            'phone.unique'      => 'Este Telefono ya se encuentra registrado',
            'phone.numeric'      => 'Este campo es numerico',
            'email.required'    => 'Introduzca el correo electrónico',
            'email.regex'       => 'Introduzca un correo electrónico valido ejemplo xxx@hotelfarsund.es',
            'email.unique'      => 'Este email ya se encuentra registrado',
            'password.required' => 'Introduzca la contraseña',
        ]);

        $administrator = new User($request->all());
        $administrator->admin = true;
        $administrator->save();
        return redirect()->route('administrator.index')->with('success', 'Usuario registrado sastifactoriamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $administrator = User::findOrFail($id);
        return view('administrator.user.administrators.edit')->with('administrator', $administrator);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {   
        request()->validate([
            'firstname'  => 'required',
            'lastname'   => 'required',
            'dni'        => 'required|unique:users,dni,'. $id,
            'phone'      => 'required|numeric|unique:users,phone,'. $id,
            'email'      => 'required|regex:/(.*)@hotelfarsund\.es$/i|unique:users,email,'. $id,
        ],
        [
            'firstname.required'    => 'Introduzca el nombre',
            'lastname.required'     => 'Introduzca el apellido',
            'dni.required'      => 'Introduzca el DNI',
            'dni.unique'        => 'Este DNI ya se encuentra registrado',
            'phone.required'    => 'Introduzca el Telefono',
            'phone.unique'      => 'Este Telefono ya se encuentra registrado',
            'phone.numeric'     => 'Este campo es numerico',
            'email.required'    => 'Introduzca el correo electrónico',
            'email.regex'       => 'Introduzca un correo electrónico valido ejemplo xxx@hotelfarsund.es',
            'email.unique'      => 'Este email ya se encuentra registrado',
        ]);

        User::findOrFail($id)->update(['email' => $request->email,
                                       'firstname' => $request->firstname,
                                       'lastname' => $request->lastname,
                                       'dni' => $request->dni,
                                       'phone' => $request->phone
                                      ]);
        
        return redirect()->route('administrator.index')->with('success', 'Usuario actualizado sastifactoriamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $extra = User::find($id)->delete();
        return redirect()->route('administrator.index');
    }
}

app/Http/Controllers/Dashboard/ExtraController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Extra;
use App\Models\RoomType;

class ExtraController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {set_time_limit("1800");
        $extras = Extra::orderBy('name')->get();
        $roomTypes = RoomType::all();
        return view('administrator.extras.index')
        ->with('extras',$extras)
        ->with('roomTypes',$roomTypes);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('administrator.extras.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $extra = new Extra($request->all());
        $extra->save();

        return redirect()->route('extra.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $extra = Extra::find($id);
        return view('administrator.extras.edit')->with('extra',$extra);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        request()->validate([
            'name'   => 'required|unique:extras,name,'. $id,
            'price'  => 'required|numeric'
        ],
        [
            'name.required'  => 'Introduzca el extra',
            'name.unique'    => 'Este extra ya se encuentra registrado',
            'price.required' => 'Introduzca el precio',
            'price.numeric'  => 'Este campo es nuemrico',
        ]);

        Extra::findOrFail($id)->update(['name' => $request->name, 'price' => $request->price]);
        
        return redirect()->route('extra.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $extra = Extra::find($id)->delete();
        return redirect()->route('extra.index');
    }
}

resources/views/administrator/extras/create.blade.php
@extends('administrator.layouts.app')

@section('module-active')
<li class="breadcrumb-item active">Crear Extra</li>
@endsection
@section('content')
<section id="main-content">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-title">
                    <h4>Crear Extra</h4>

                </div>
                <div class="card-body">
                    <div class="basic-elements">

                        <form method="post" action="{{route('extra.store')}}">
                            @csrf
                            <div class="form-group">
                                <label for="exampleFormControlTextarea1">Extra</label>
                                <input type="text" name="name" class="form-control input-rounded">
                            </div>

                            <div class="form-group">
                                <label for="exampleFormControlTextarea1">Precio</label>
                                <input type="number" name="price" class="form-control input-rounded">
                            </div>

                            <div class="form-group">
                                <div class="form-check">
                                    <input name="optional" class="form-check-input" type="checkbox" id="defaultCheck1">
                                    <label class="form-check-label" for="defaultCheck1">
                                        Opcional
                                    </label>
                                </div>
                            </div>

                            <br><br>
                            <div class="row align-items-end">
                                <button type="submit" class="btn btn-farsund left">Guardar</button>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>

    </div>
    <!-- /# row -->
</section>



<div class="section padding-top-bottom-smaller background-dark-2 over-hide">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">

            </div>
        </div>
    </div>
</div>
@endsection

resources/views/administrator/extras/edit.blade.php
@extends('administrator.layouts.app')
@section('module-active')
<li class="breadcrumb-item active">Editar extra</li>
@endsection
@section('content')
<section id="main-content">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-title">
                    <h4>Editar extra</h4>

                </div>
                <div class="card-body">
                    <div class="basic-elements">

                        <form method="post" action="{{route('extra.update', $extra->id)}}">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label for="exampleFormControlTextarea1">Extra</label>
                                <input type="text" class="form-control input-rounded" id="exampleFormControlInput1" name="name"
                                    value="{{$extra->name}}">
                            </div>

                            <div class="form-group">
                                <label for="exampleFormControlTextarea1">Precio</label>
                                <input type="number" class="form-control input-rounded" id="exampleFormControlInput1" name="price"
                                    value="{{$extra->price}}">
                            </div>

                            <br><br>
                            <div class="row align-items-end">
                                <button type="submit" class="btn btn-farsund left">Guardar</button>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>

    </div>
    <!-- /# row -->
</section>



<div class="section padding-top-bottom-smaller background-dark-2 over-hide">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">

            </div>
        </div>
    </div>
</div>
@endsection

resources/views/administrator/extras/index.blade.php
@extends('administrator.layouts.app')
@section('module-active')
<li class="breadcrumb-item active">Administradores</li>
@endsection
@section('content')


<section id="main-content">
    <div class="col-md-12">
        <a href="{{route('extra.create')}}" class="btn btn-farsund">Crear extra</a>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="bootstrap-data-table-panel">
                    <div class="table-responsive">
                        <table id="bootstrap-data-table-export" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>Extras</th>
                                    <th>Precio</th>
                                    <th></th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($extras as $extra)
                                <tr>
                                    <td>{{$extra->name}}</td>
                                    <td>{{$extra->price}}</td>
                                    <td style="text-align:center"><a
                                            class="btn btn-farsund btn-flat btn-addon m-b-10 m-l-5"
                                            href="{{route('extra.edit', $extra->id)}}" role="button"><i
                                                class="ti-settings"></i>Editar</a></td>
                                    <td style="text-align:center">
                                        <form action="{{ route('extra.destroy' , $extra->id)}}" method="POST">
                                            @csrf
                                            @method("DELETE")
                                            <button type="submit" class="btn btn-farsund">Eliminar</button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- /# card -->
        </div>
        <!-- /# column -->
    </div>
    <!-- /# row -->
</section>

@endsection