routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Dashboard\ProfileController;
use App\Http\Controllers\Dashboard\BookingController;
use App\Http\Controllers\Dashboard\RoomTypeController;
use App\Http\Controllers\Dashboard\RoomController;
use App\Http\Controllers\Dashboard\GuestController;
use App\Http\Controllers\Dashboard\AdministratorController;
use App\Http\Controllers\Dashboard\RestrictionController;
use App\Http\Controllers\Dashboard\ExtraController;
use App\Http\Controllers\Dashboard\OrderController;
use App\Http\Controllers\Dashboard\ServiceController;

use App\Http\Controllers\Portal\HotelFarsundController;
use App\Http\Controllers\Portal\BookingPaymentController;
use App\Http\Controllers\Auth\UserController;
use App\Http\Controllers\LenguageController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HotelFarsundController::class, 'home'])->name('home');
Route::get('sobre-nosotros', [HotelFarsundController::class, 'about'])->name('about');
Route::get('habitaciones', [HotelFarsundController::class, 'rooms'])->name('rooms');
Route::get('reservar/{id}/{chechin?}/{checkout?}', [HotelFarsundController::class, 'book'])->name('book');
Route::get('servicios', [HotelFarsundController::class, 'services'])->name('services');
Route::get('lugares-de-interes', [HotelFarsundController::class, 'placeInterest'])->name('places_interest');
Route::get('contacto', [HotelFarsundController::class, 'contact'])->name('contact');
Route::post('contacto/enviar', [HotelFarsundController::class, 'send'])->name('send.contact');
Route::get('policy-privacy', [HotelFarsundController::class, 'policyPrivacy'])->name('policy.privacy');
Route::get('terms-conditions', [HotelFarsundController::class, 'termsConditions'])->name('terms.conditions');


Route::middleware(['guest'])->group(function () {
    /* User - Farsund */    
    Route::get('sig-up', [UserController::class, 'create'])->name('create.user');
    Route::post('sig-up/store', [UserController::class, 'store'])->name('store.user');
    Route::get('sig-in', [UserController::class, 'login'])->name('login');
    Route::post('sig-in/authentication', [UserController::class, 'authentication'])->name('authentication');
});

Route::middleware('auth')->group(function(){
    /* User - Farsund */    
    Route::get('logout', [UserController::class, 'logout'])->name('logout.user');
    Route::post('reservacion/{room}', [BookingPaymentController::class, 'store'])->name('payment');
    Route::get('confirm', [BookingPaymentController::class, 'show'])->name('confirm');
    Route::get('approbal', [BookingPaymentController::class, 'approbal'])->name('approbal');

});



Route::group(['middleware' => 'admin', 'prefix' => 'dashboard'], function(){
    
    Route::resource('/profile', ProfileController::class);
    Route::get('/profile/edit/datos', [ProfileController::class, 'editProfile'])->name('profile.edit.datos');
    Route::PUT('/profile/update/datos', [ProfileController::class, 'updateProfile'])->name('profile.update.datos');
    Route::get('/profile/edit/password', [ProfileController::class, 'editPass'])->name('profile.edit.password');
    Route::PUT('/profile/update/password', [ProfileController::class, 'updatePass'])->name('profile.update.password');
    Route::resource('/booking', BookingController::class);
    Route::post('/booking/confirm', [BookingController::class, 'confirm'])->name('booking.confirm');
    Route::post('/booking/finish', [BookingController::class, 'finish'])->name('booking.finish');
    Route::resource('/roomtype', RoomTypeController::class);
    Route::resource('/room', RoomController::class);
    Route::resource('/guest', GuestController::class);
    Route::resource('/administrator', AdministratorController::class);
    Route::resource('/restriction', RestrictionController::class);
    Route::resource('/extra', ExtraController::class);
    Route::resource('/order', OrderController::class);
    Route::resource('/service', ServiceController::class);
    
});

/*Lenguage*/
Route::get('lang/{lang}', [LenguageController::class, 'swap'])->name('lang.swap');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = ['firstname','lastname','dni','email','phone','password','admin'];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function setEmailAttribute($value)
    {
      $this->attributes['email'] = strtolower($value);
    }  

    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = bcrypt($value);
    }




    public function bookings()
    {
        return $this->hasMany(Booking::class);
    }

    
}

app/Http/Controllers/Dashboard/GuestController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;

class GuestController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {set_time_limit("1800");
        $guests = User::where('admin', false)->get();
        return view('administrator.user.guests.index')->with('guests', $guests);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('administrator.user.guests.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'firstname'  => 'required',
            'lastname'   => 'required',
            'dni'        => 'required|unique:users,dni',
            'email'      => 'required|unique:users,email|regex:/^.+@.+$/i',
            'phone'      => ['required','numeric','unique:users,phone'],
            'password'   => 'required|min:8',
        ],
        [
            'firstname.required' => 'Introduzca el nombre',
            'lastname.required'  => 'Introduzca el apellido',
            'dni.required'       => 'Introduzca el DNI',
            'dni.unique'         => 'Este DNI ya se encuentra registrado',
            'email.required'     => 'Introduzca el correo electrónico',
            'email.unique'       => 'Este email ya se encuentra registrado',
            'phone.required'     => 'Introduzca el telefono',
            'phone.unique'       => 'Este telefono ya se encuentra registrado',
            
        ]);

        $guest = new User($request->all());
        $guest->save();

        return redirect()->route('guest.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $guest = User::findOrFail($id);
        return view('administrator.user.guests.edit')->with('guest', $guest);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        request()->validate([
            'firstname' => 'required',
            'lastname'  => 'required',
            'dni'       => 'required|unique:users,dni,'. $id,
            'email'     => 'required|unique:users,email,'. $id.'|email|regex:/^.+@.+$/',
            'phone'     => 'required|unique:users,phone,'. $id,
        ],
        [
            'firstname.required' => 'Introduzca el nombre',
            'lastname.required'  => 'Introduzca el apellido',
            'dni.required'       => 'Introduzca el DNI',
            'dni.unique'         => 'Este DNI ya se encuentra registrado',
            'email.required'     => 'Introduzca el correo electrónico',
            'email.unique'       => 'Este email ya se encuentra registrado',
            'phone.required'     => 'Introduzca el telefono',
            'phone.unique'       => 'Este telefono ya se encuentra registrado',
        ]);

        User::findOrFail($id)->update(['firstname' => $request->firstname,'lastname' => $request->lastname,
                                       'dni' => $request->dni,'email' => $request->email,'phone' => $request->phone]);
        
        return redirect()->route('guest.index')->with('success', 'Huesped actualizado sastifactoriamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        dd("En desarrollo");
    }
}

resources/views/administrator/user/guests/create.blade.php
@extends('administrator.layouts.app')
@section('module-active')
<li class="breadcrumb-item active">Registrar Huesped</li>
@endsection
@section('content')
<section id="main-content">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-title">
                    <h4>Registrar Huesped</h4>

                </div>
                <div class="card-body">
                    <div class="basic-elements">
                        <form method="post" action="{{route('guest.store')}}" enctype="multipart/form-data">
                            @csrf
                            <div class="row">
                                <div class="col-lg-4">
                                    <div class="form-group">
                                        <label for="exampleFormControlTextarea1">Nombre</label>
                                        <input type="text" name="firstname" class="form-control input-rounded">
                                    </div>
                                </div>
                                <div class="col-lg-4">
                                    <div class="form-group">
                                        <label for="exampleFormControlTextarea1">Apellido</label>
                                        <input type="text" name="lastname" class="form-control input-rounded">
                                    </div>
                                </div>
                                <div class="col-lg-4">
                                    <div class="form-group">
                                        <label for="exampleFormControlTextarea1">DNI</label>
                                        <input type="number" name="dni" class="form-control input-rounded">
                                    </div>
                                </div>
                                <div class="col-lg-4">
                                    <div class="form-group">
                                        <label for="exampleFormControlTextarea1">Correo electronico</label>
                                        <input type="email" name="email" class="form-control input-rounded">
                                    </div>
                                </div>
                                <div class="col-lg-4">
                                    <div class="form-group">
                                        <label for="exampleFormControlTextarea1">Contraseña</label>
                                        <input type="password" name="password" class="form-control input-rounded">
                                    </div>
                                </div>
                            </div>
                    </div>
                    <button class="btn btn-farsund">Guardar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    </div>
    <!-- /# row -->



</section>



<div class="section padding-top-bottom-smaller background-dark-2 over-hide">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">

            </div>
        </div>
    </div>
</div>
@endsection

resources/views/administrator/user/guests/edit.blade.php
@extends('administrator.layouts.app')
@section('module-active')
<li class="breadcrumb-item active">Actualizar Usuario</li>
@endsection
@section('content')
<section id="main-content">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-title">
                    <h4>Actualizar usuario</h4>

                </div>
                <div class="card-body">
                    <div class="basic-elements">
                        <form method="post" action="{{route('guest.update', $guest->id)}}"
                            enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="row">
                                <div class="col-lg-4">
                                    <div class="form-group">
                                        <label for="exampleFormControlTextarea1">Nombre</label>
                                        <input type="text" name="firstname" class="form-control input-rounded" value="{{$guest->firstname}}">
                                    </div>
                                </div>
                                <div class="col-lg-4">
                                    <div class="form-group">
                                        <label for="exampleFormControlTextarea1">Apellido</label>
                                        <input type="text" name="lastname" class="form-control input-rounded" value="{{$guest->lastname}}">
                                    </div>
                                </div>
                                <div class="col-lg-4">
                                    <div class="form-group">
                                        <label for="exampleFormControlTextarea1">DNI</label>
                                        <input type="number" name="dni" class="form-control input-rounded" value="{{$guest->dni}}">
                                    </div>
                                </div>
                                <div class="col-lg-4">
                                    <div class="form-group">
                                        <label for="exampleFormControlTextarea1">Correo electronico</label>
                                        <input type="email" name="email" class="form-control input-rounded" value="{{$guest->email}}">
                                    </div>
                                </div>
                                <div class="col-lg-4">
                                    <div class="form-group">
                                        <label for="exampleFormControlTextarea1">Telefono</label>
                                        <input type="number" name="phone" class="form-control input-rounded" value="{{$guest->phone}}">
                                    </div>
                                </div>
                                <div class="col-lg-4">
                                    <div class="form-group">
                                        <label for="exampleFormControlTextarea1">Telefono</label>
                                        <input type="number" name="phone" class="form-control input-rounded" value="{{$guest->phone}}">
                                    </div>
                                </div>
                            </div>
                    </div>
                    <button class="btn btn-farsund">Guardar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    </div>
    <!-- /# row -->



</section>



<div class="section padding-top-bottom-smaller background-dark-2 over-hide">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">

            </div>
        </div>
    </div>
</div>
@endsection

resources/views/administrator/user/guests/index.blade.php
@extends('administrator.layouts.app')
@section('module-active')
<li class="breadcrumb-item active">Administradores</li>
@endsection
@section('content')


<section id="main-content">
    <div class="col-md-12">
        <a href="{{route('guest.create')}}" class="btn btn-farsund">Nuevo Huesped</a>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="bootstrap-data-table-panel">
                    <div class="table-responsive">
                        <table id="bootstrap-data-table-export" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>Nombre completo</th>
                                    <th>DNI</th>
                                    <th>Telefono</th>
                                    <th>Correo electrónico</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($guests as $guest)
                                <tr>
                                    <td>{{$guest->firstname}} {{$guest->lastname}}</td>
                                    <td>{{$guest->dni}}</td>
                                    <td>{{$guest->phone}}</td>
                                    <td>{{$guest->email}}</td>
                                    <td><a class="btn btn-farsund btn-flat btn-addon m-b-10 m-l-5"
                                            href="{{route('guest.edit', $guest->id)}}" role="button"><i
                                                class="ti-settings"></i> Editar</a></td>
                                    <td style="text-align:center">
                                        <form action="{{ route('guest.destroy' , $guest->id)}}" method="POST">
                                            @csrf
                                            @method("DELETE")
                                            <button type="submit" class="btn btn-farsund">Eliminar</button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- /# card -->
        </div>
        <!-- /# column -->
    </div>
    <!-- /# row -->
</section>

@endsection