routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Dashboard\ProfileController;
use App\Http\Controllers\Dashboard\BookingController;
use App\Http\Controllers\Dashboard\RoomTypeController;
use App\Http\Controllers\Dashboard\RoomController;
use App\Http\Controllers\Dashboard\GuestController;
use App\Http\Controllers\Dashboard\AdministratorController;
use App\Http\Controllers\Dashboard\RestrictionController;
use App\Http\Controllers\Dashboard\ExtraController;
use App\Http\Controllers\Dashboard\OrderController;
use App\Http\Controllers\Dashboard\ServiceController;

use App\Http\Controllers\Portal\HotelFarsundController;
use App\Http\Controllers\Portal\BookingPaymentController;
use App\Http\Controllers\Auth\UserController;
use App\Http\Controllers\LenguageController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HotelFarsundController::class, 'home'])->name('home');
Route::get('sobre-nosotros', [HotelFarsundController::class, 'about'])->name('about');
Route::get('habitaciones', [HotelFarsundController::class, 'rooms'])->name('rooms');
Route::get('reservar/{id}/{chechin?}/{checkout?}', [HotelFarsundController::class, 'book'])->name('book');
Route::get('servicios', [HotelFarsundController::class, 'services'])->name('services');
Route::get('lugares-de-interes', [HotelFarsundController::class, 'placeInterest'])->name('places_interest');
Route::get('contacto', [HotelFarsundController::class, 'contact'])->name('contact');
Route::post('contacto/enviar', [HotelFarsundController::class, 'send'])->name('send.contact');
Route::get('policy-privacy', [HotelFarsundController::class, 'policyPrivacy'])->name('policy.privacy');
Route::get('terms-conditions', [HotelFarsundController::class, 'termsConditions'])->name('terms.conditions');


Route::middleware(['guest'])->group(function () {
    /* User - Farsund */    
    Route::get('sig-up', [UserController::class, 'create'])->name('create.user');
    Route::post('sig-up/store', [UserController::class, 'store'])->name('store.user');
    Route::get('sig-in', [UserController::class, 'login'])->name('login');
    Route::post('sig-in/authentication', [UserController::class, 'authentication'])->name('authentication');
});

Route::middleware('auth')->group(function(){
    /* User - Farsund */    
    Route::get('logout', [UserController::class, 'logout'])->name('logout.user');
    Route::post('reservacion/{room}', [BookingPaymentController::class, 'store'])->name('payment');
    Route::get('confirm', [BookingPaymentController::class, 'show'])->name('confirm');
    Route::get('approbal', [BookingPaymentController::class, 'approbal'])->name('approbal');

});



Route::group(['middleware' => 'admin', 'prefix' => 'dashboard'], function(){
    
    Route::resource('/profile', ProfileController::class);
    Route::get('/profile/edit/datos', [ProfileController::class, 'editProfile'])->name('profile.edit.datos');
    Route::PUT('/profile/update/datos', [ProfileController::class, 'updateProfile'])->name('profile.update.datos');
    Route::get('/profile/edit/password', [ProfileController::class, 'editPass'])->name('profile.edit.password');
    Route::PUT('/profile/update/password', [ProfileController::class, 'updatePass'])->name('profile.update.password');
    Route::resource('/booking', BookingController::class);
    Route::post('/booking/confirm', [BookingController::class, 'confirm'])->name('booking.confirm');
    Route::post('/booking/finish', [BookingController::class, 'finish'])->name('booking.finish');
    Route::resource('/roomtype', RoomTypeController::class);
    Route::resource('/room', RoomController::class);
    Route::resource('/guest', GuestController::class);
    Route::resource('/administrator', AdministratorController::class);
    Route::resource('/restriction', RestrictionController::class);
    Route::resource('/extra', ExtraController::class);
    Route::resource('/order', OrderController::class);
    Route::resource('/service', ServiceController::class);
    
});

/*Lenguage*/
Route::get('lang/{lang}', [LenguageController::class, 'swap'])->name('lang.swap');

app/Http/Controllers/Dashboard/AdministratorController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;

class AdministratorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {set_time_limit("1800");
        $administrators = User::where('admin', true)->where('id', '<>', auth()->id())->get();
        return view('administrator.user.administrators.index')->with('administrators', $administrators);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('administrator.user.administrators.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'firstname'  => 'required',
            'lastname'   => 'required',
            'dni'        => 'required|unique:users,dni',
            'phone'      => 'required|numeric|unique:users,phone',
            'email'      => 'required|regex:/(.*)@hotelfarsund\.es$/i|unique:users,email',
            'password'   => 'required|min:8|',
        ],
        [
            'firstname.required'    => 'Introduzca el nombre',
            'lastname.required'     => 'Introduzca el apellido',
            'dni.required'      => 'Introduzca el DNI',
            'dni.unique'        => 'Este DNI ya se encuentra registrado',
            'phone.required'    => 'Introduzca el Telefono',
            'phone.unique'      => 'Este Telefono ya se encuentra registrado',
            'phone.numeric'      => 'Este campo es numerico',
            'email.required'    => 'Introduzca el correo electrónico',
            'email.regex'       => 'Introduzca un correo electrónico valido ejemplo xxx@hotelfarsund.es',
            'email.unique'      => 'Este email ya se encuentra registrado',
            'password.required' => 'Introduzca la contraseña',
        ]);

        $administrator = new User($request->all());
        $administrator->admin = true;
        $administrator->save();
        return redirect()->route('administrator.index')->with('success', 'Usuario registrado sastifactoriamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $administrator = User::findOrFail($id);
        return view('administrator.user.administrators.edit')->with('administrator', $administrator);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {   
        request()->validate([
            'firstname'  => 'required',
            'lastname'   => 'required',
            'dni'        => 'required|unique:users,dni,'. $id,
            'phone'      => 'required|numeric|unique:users,phone,'. $id,
            'email'      => 'required|regex:/(.*)@hotelfarsund\.es$/i|unique:users,email,'. $id,
        ],
        [
            'firstname.required'    => 'Introduzca el nombre',
            'lastname.required'     => 'Introduzca el apellido',
            'dni.required'      => 'Introduzca el DNI',
            'dni.unique'        => 'Este DNI ya se encuentra registrado',
            'phone.required'    => 'Introduzca el Telefono',
            'phone.unique'      => 'Este Telefono ya se encuentra registrado',
            'phone.numeric'     => 'Este campo es numerico',
            'email.required'    => 'Introduzca el correo electrónico',
            'email.regex'       => 'Introduzca un correo electrónico valido ejemplo xxx@hotelfarsund.es',
            'email.unique'      => 'Este email ya se encuentra registrado',
        ]);

        User::findOrFail($id)->update(['email' => $request->email,
                                       'firstname' => $request->firstname,
                                       'lastname' => $request->lastname,
                                       'dni' => $request->dni,
                                       'phone' => $request->phone
                                      ]);
        
        return redirect()->route('administrator.index')->with('success', 'Usuario actualizado sastifactoriamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $extra = User::find($id)->delete();
        return redirect()->route('administrator.index');
    }
}

resources/views/administrator/layouts/app.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    @if(in_array(Route::currentRouteName(),
    ['booking.index']))
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    @endif
    <title>Farsund</title>

    @include('administrator.layouts.head')
    @yield('css')
</head>

<body>
    <!-- sidebar -->
    @include('administrator.layouts.sidebar')
    <!-- header -->
    @include('administrator.layouts.header')

    
    <div class="content-wrap">
        <div class="main">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-8 p-r-0 title-margin-right"></div>
                    <!-- /# column -->
                    <div class="col-lg-4 p-l-0 title-margin-left">
                        <div class="page-header">
                            <div class="page-title">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
                                    @yield('module-active')
                                </ol>
                            </div>
                        </div>
                    </div>
                    <!-- /# column -->
                </div>
                <!-- /# row -->

				<!-- Content ===== -->
				@yield('content')
            </div>
        </div>
    </div>

    @include('administrator.layouts.footer')
    @yield('js')
</body>

</html>

resources/views/administrator/layouts/footer.blade.php
    <script src="{{ asset('administrator/js/lib/jquery.min.js') }}"></script>
	<script src="{{ asset('administrator/js/lib/jquery.nanoscroller.min.js') }}"></script>
	<script src="{{ asset('administrator/js/lib/menubar/sidebar.js') }}"></script>
	<script src="{{asset('administrator/js/lib/bootstrap.min.js')}}"></script>  
	<script src="{{asset('administrator/js/scripts.js')}}"></script> 
	@if(in_array(Route::currentRouteName(),
    [
        'room.index',
        'booking.index'
    ]))
	<script src="{{asset('administrator/js/lib/jquery-ui/jquery-ui.min.js')}}"></script>
  	<script src="{{asset('administrator/js/lib/moment/moment.js')}}"></script>
  	<script src="{{asset('administrator/js/lib/calendar/fullcalendar.js')}}"></script>
  	<script src="{{asset('administrator/js/lib/calendar/es.js')}}"></script>
  	<script src="{{asset('administrator/js/toastr.min.js')}}"></script>
  	<script src="{{asset('administrator/js/toastr.init.js')}}"></script>
	@endif

resources/views/administrator/layouts/head.blade.php
	<!-- ================= Favicon ================== -->
    <!-- Standard -->
    <link rel="shortcut icon" href="http://placehold.it/64.png/000/fff">
    <!-- Retina iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="144x144" href="http://placehold.it/144.png/000/fff">
    <!-- Retina iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="114x114" href="http://placehold.it/114.png/000/fff">
    <!-- Standard iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="72x72" href="http://placehold.it/72.png/000/fff">
    <!-- Standard iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="57x57" href="http://placehold.it/57.png/000/fff">
	
	<link href="{{ asset('administrator/css/lib/font-awesome.min.css') }}" rel="stylesheet">
	<link href="{{ asset('administrator/css/lib/themify-icons.css') }}" rel="stylesheet">
	<link href="{{ asset('administrator/css/lib/menubar/sidebar.css') }}" rel="stylesheet">
	<link href="{{ asset('administrator/css/lib/bootstrap.min.css') }}" rel="stylesheet">
	<link href="{{ asset('administrator/css/lib/helper.css') }}" rel="stylesheet">	
	<link href="{{ asset('administrator/css/style.css') }}" rel="stylesheet">
    @if(in_array(Route::currentRouteName(),
    [
        'room.index',
        'booking.index'
    
    ]))
    <!-- Toastr -->
    <link href="{{ asset('administrator/css/lib/toastr/toastr.min.css') }}" rel="stylesheet">
    <!-- Sweet Alert -->
    <link href="{{ asset('administrator/css/lib/sweetalert/sweetalert.css') }}" rel="stylesheet">
    <!-- JsGrid -->
    <link href="{{ asset('administrator/css/lib/jsgrid/jsgrid-theme.min.css') }}" rel="stylesheet">
    <link href="{{ asset('administrator/css/lib/jsgrid/jsgrid.min.css') }}" rel="stylesheet">
    <!-- Datatable -->
    <link href="{{ asset('administrator/css/lib/datatable/dataTables.bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('administrator/css/lib/data-table/buttons.bootstrap.min.css') }}" rel="stylesheet">
    <!-- Owl Carousel -->
    <link href="{{ asset('administrator/css/lib/owl.carousel.min.css') }}" rel="stylesheet">
    <link href="{{ asset('administrator/css/lib/owl.theme.default.min.css') }}" rel="stylesheet">
    <!-- Select2 -->
    <link href="{{ asset('administrator/css/lib/select2/select2.min.css') }}" rel="stylesheet">
    <!-- Calender -->
    <link href="{{ asset('administrator/css/lib/calendar/fullcalendar.css') }}" rel="stylesheet">
    <style>
        .fc-title{
            font-weight: bold;
            color:#fff;
        }
        .fc-time{
            /* display: none; */
            color:red;
        }
    </style>
    @endif

resources/views/administrator/layouts/header.blade.php
<div class="header">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="float-left">
                        <div class="hamburger sidebar-toggle">
                            <span class="line"></span>
                            <span class="line"></span>
                            <span class="line"></span>
                        </div>
                    </div>
                    <div class="float-right">
                        <!-- <div class="dropdown dib">
                            <div class="header-icon" data-toggle="dropdown">
                                <i class="ti-bell"></i>
                                <div class="drop-down dropdown-menu dropdown-menu-right">
                                    <div class="dropdown-content-heading">
                                        <span class="text-left">Recent Notifications</span>
                                    </div>
                                    <div class="dropdown-content-body">
                                        <ul>
                                            <li>
                                                <a href="#">
                                                    <img class="pull-left m-r-10 avatar-img" src="assets/images/avatar/3.jpg" alt="" />
                                                    <div class="notification-content">
                                                        <small class="notification-timestamp pull-right">02:34 PM</small>
                                                        <div class="notification-heading">Mr. John</div>
                                                        <div class="notification-text">5 members joined today </div>
                                                    </div>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="#">
                                                    <img class="pull-left m-r-10 avatar-img" src="assets/images/avatar/3.jpg" alt="" />
                                                    <div class="notification-content">
                                                        <small class="notification-timestamp pull-right">02:34 PM</small>
                                                        <div class="notification-heading">Mariam</div>
                                                        <div class="notification-text">likes a photo of you</div>
                                                    </div>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="#">
                                                    <img class="pull-left m-r-10 avatar-img" src="assets/images/avatar/3.jpg" alt="" />
                                                    <div class="notification-content">
                                                        <small class="notification-timestamp pull-right">02:34 PM</small>
                                                        <div class="notification-heading">Tasnim</div>
                                                        <div class="notification-text">Hi Teddy, Just wanted to let you ...</div>
                                                    </div>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="#">
                                                    <img class="pull-left m-r-10 avatar-img" src="assets/images/avatar/3.jpg" alt="" />
                                                    <div class="notification-content">
                                                        <small class="notification-timestamp pull-right">02:34 PM</small>
                                                        <div class="notification-heading">Mr. John</div>
                                                        <div class="notification-text">Hi Teddy, Just wanted to let you ...</div>
                                                    </div>
                                                </a>
                                            </li>
                                            <li class="text-center">
                                                <a href="#" class="more-link">See All</a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div> -->
                    
                        <div class="dropdown dib">
                            <div class="header-icon" data-toggle="dropdown">
                                <span class="user-avatar">{{ Auth::user()->firstname }}
                                    <i class="ti-angle-down f-s-10"></i>
                                </span>
                                <div class="drop-down dropdown-profile dropdown-menu dropdown-menu-right">
                                    <div class="dropdown-content-body">
                                        <ul>
                                            <li>
                                                <a href="{{route('profile.index')}}">
                                                    <i class="ti-user"></i>
                                                    <span>Perfil</span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="{{ url('logout') }}">
                                                    <i class="ti-power-off"></i>
                                                    <span>Cerrar Sesión</span>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

resources/views/administrator/layouts/sidebar.blade.php
<div class="sidebar sidebar-hide-to-small sidebar-shrink sidebar-gestures">
      <div class="nano">
        <div class="nano-content">
          <div class="logo"><a href="#"><!-- <img src="assets/images/logo.png" alt="" /> --><span>Hotel Farsund</span></a></div>
          <ul>
            <li class="label">Administración</li>
            <li><a href="{{route('profile.index')}}"><i class="ti-user"></i> Dashboard</a></li>
            <li><a href="{{route('booking.index')}}"><i class="ti-calendar"></i> Rerservas </a></li>
            <li><a href="{{route('roomtype.index')}}"><i class="ti-home"></i> Tipo de Habitaciones </a></li>
            <li><a href="{{route('room.index')}}"><i class="ti-home"></i> Habitaciones </a></li>
            <li><a href="{{route('guest.index')}}"><i class="ti-user"></i> Huéspedes </a></li>
            <li><a href="{{route('administrator.index')}}"><i class="ti-user"></i> Administradores</a></li>
            <li><a href="{{route('restriction.index')}}"><i class="ti-home"></i> Restricciones</a></li>
            <li><a href="{{route('extra.index')}}"><i class="ti-home"></i> Extras - Habitación</a></li>
            <li><a href="{{route('order.index')}}"><i class="ti-home"></i> Ordenes</a></li>
            <li><a href="{{route('service.index')}}"><i class="ti-view-list-alt"></i> Servicios Hotel </a></li>
            <li><a href="{{route('home')}}"><i class="ti-world"></i> Hotel Farsund</a></li> 
            <li><a href="{{route('logout.user')}}"><i class="ti-power-off"></i> Cerrar Sesión</a></li>
          </ul>
        </div>
      </div>
    </div>